### ISSUE TITLE
overlayClose

### ISSUE THREAD

**Issue by MatheusR42** [dolce/iziModal#1]
Primeiramente, parabéns pelo plugin, com certeza irei utiliza-lo.

"Segundamente", estava testando as funcionalidades no site oficial e percebi que a função overlayClose só funciona da primeira vez que a modal é aberta, uma vez fechada, tanto pelo botão "X" quanto clicando ao fundo, quando a modal for aberta novamente o único modo fecha-la é clicando no botão "X".

Testes efetuados no Chromium e Firefox

**Comment by dolce** [comment]
obrigado por reportar @MatheusR42, realmente não tinha reparado neste bug, vou corrigir o quanto antes!

**Comment by dolce** [comment]
Corrigido @MatheusR42, já atualizei o site e o repositório, abçs!
