### ISSUE TITLE
Izimodal opens and closes immediately

### ISSUE THREAD

**Issue by karedas** [dolce/iziModal#106]
I used izimodal on several occasions and it often happens that if I launch the "open" method right after izimodal initialization, modal opens and immediately autocloses.

es:
```
$('#element').iziModal({
options...
});

$(#element).iziModal('open');

```

I know the "autoopen" option exists to  prevent this from happening but it is not the case that you often use it, since sometimes there are some occurrences or controls that need the ".izimodal ('open') method between somes check ("if", controls that set the "open" or not .. ). I did a little check on the logic of the script and I noticed that Izimodal is doing a "close" method in the init  that apparently contrasts with what was said above.

Has anyone encountered the same problem?

**Comment by RyanGosden** [comment]
I ran into the same issue also. If you immediately click to open the modal, the modal will open and close.

**Comment by fjeddy** [comment]
Same issue here, opening the modal instantly on page load will close it again right away. Seems like some other javascript function is telling the modal to close.

**Comment by dolce** [comment]
I will analyze.
But if you want to open soon after instializing iziModal, use a setTimeout.
```
setTimeout(function(){
	$('#element').iziModal('open');
},100)
```
See if it works.

**Comment by dolce** [comment]
Can you put the example online with this problem mentioned?

**Comment by fjeddy** [comment]
Using `setTimout` works and was and is my current solution. Tho, it shouldn't be necessary to do so? It also seems to work better to initialize the iziModal inside the click event then initializing it before hand.

**Comment by dolce** [comment]
Hello, could you test this new version?
[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271677/iziModal_v1.5.1.zip)

You will be able to use **appendToOverlay** option and the new methods: **setContent** and **reset**.
`$('#modal').iziModal('setContent', '<div>Content</div>');`
`$('#modal').iziModal('reset');`

And **afterRender** callback:
`afterRender: function(){}`

**Comment by juanpasolano** [comment]
@dolce zip file v1.5.1 working like a charm. Bug gone in my case

**Comment by fjeddy** [comment]
Sorry, i moved on to making a custom solution for this specific scenario to make it work as i wanted it. Doing an entire website inside iziModal was not ideal :( :P
