### ISSUE TITLE
Auto close on URL change

### ISSUE THREAD

**Issue by fjeddy** [dolce/iziModal#116]
If the hash and or URI changes while the modal is open, then it will automatically close. How can I prevent this behavior?

**Comment by dolce** [comment]
Can you put the example online with this problem?

**Comment by dolce** [comment]
Hello @fjeddy , could you test this new version?
[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271677/iziModal_v1.5.1.zip)

You will be able to use **appendToOverlay** option and the new methods: **setContent** and **reset**.
`$('#modal').iziModal('setContent', '<div>Content</div>');`
`$('#modal').iziModal('reset');`

And **afterRender** callback:
`afterRender: function(){}`
