### ISSUE TITLE
Close modal not supported in IE9 with "data-" attribute. 'Opened' state not setted

### ISSUE THREAD

**Issue by orney21d** [dolce/iziModal#117]
Hi,
The close modal functionality throught data-attribute is not working in "IE-9":
I have for example following button:

`<button data-izimodal-close="" type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
            Test Close
        </button>`

The default initialization for modal are:

` $("#tag_modal").iziModal({
            title: '',
            subtitle: '',
            headerColor: '#88A0B9',
            theme: '',  // light
            attached: '', // bottom, top
            icon: '',
            iconColor: '',
            width: 600,
            padding: 0,
            radius: 3,
            zindex: 999,
            iframe: false,
            iframeHeight: 400,
            iframeURL: null,
            focusInput: true,
            group: '',
            loop: false,
            navigateCaption: true,
            navigateArrows: true, // closeToModal, closeScreenEdge
            history: true,
            restoreDefaultContent: false,
            autoOpen: 0, // Boolean, Number
            bodyOverflow: true,
            fullscreen: false,
            openFullscreen: false,
            closeOnEscape: true,
            overlay: true,
            overlayClose: false,
            overlayColor: 'rgba(0, 0, 0, 0.4)',
            timeout: false,
            timeoutProgressbar: false,
            pauseOnHover: false,
            timeoutProgressbarColor: 'rgba(255,255,255,0.5)',
            transitionIn: 'comingIn',
            transitionOut: 'comingOut',
            transitionInOverlay: 'fadeIn',
            transitionOutOverlay: 'fadeOut',
            onFullscreen: function () { },
            onResize: function () { },
            onOpening: function () { },
            onOpened: function () { },
            onClosing: function () { },
            onClosed: function () { }
        });`

**Comment by orney21d** [comment]
What i sow is happening is that in IE9 the Modal handlers "onOpened" is not firing after modal is open, even setting that state in my object. In IE9 just firing "onOpening" and "onClosing" handlers: 

The fact is that i'm attached to "closed" event to close and destroy Modal, i have something like following, i insert what i think is the relevant code in the instantiation process of Modal:
`
         //This function is called in instantiation process
         init: function () {

                    this.modal = $("#fefe_modal").iziModal(this.settings);
                    this.modal.iziModal('destroy');
                    //Recreando  el modal
                    this.modal = $("#fefe_modal").iziModal(this.settings);

                    $("#fefe_modal").css("top", "0%");
                    this.bindEvents();
                },

                 //Binding to "closed" event
                bindEvents: function () {
                    $('#fefe_modal').on('closed', this.modal, $.proxy(this.destroyModal, this));

                },

                //Handler attached to "closed" event. Never call this in IE 9
                destroyModal: function (event) {

                    event.preventDefault();
                    event.stopPropagation();
                    $(this.modal).off('closed', $.proxy(this.destroyModal, this));
                    $.setFefeModalHtml(this.modal, '');
                    this.modal.iziModal('destroy');

                    /*Removing classes that let Modal when destroyed & adding classes in initialization state */
                    $("#fefe_modal").removeClass("isFullscreen isAttached").addClass("modal-content col-xs-12 col-sm-8 col-md-8");
                    location.hash = "_";
                    return;
                }`

**Comment by orney21d** [comment]
I sow too that in IE9  the modal is not setting "Opened" state after open it.... The modal remain in "Opening" state, maybe for that reason the "Closed" state never is fire in "IE9"

**Comment by orney21d** [comment]
Hi, i have resolved it, i sow that for setting "Opened" and "Closed" states you ask for a condition for example for "Opened" state:

`
                                   if (transitionIn !== '') {

							that.$element.addClass("transitionIn "+transitionIn).show();
							that.$wrap.one(animationEvent, function () {

							    that.$element.removeClass(transitionIn + " transitionIn");
							    that.$overlay.removeClass(that.options.transitionInOverlay);
							    that.$navigate.removeClass(that.options.transitionInOverlay);

								opened();
							});

		                   } else {
						that.$element.show();
						opened();
				}`

The fact is that in **IE9** the transitions not working, and the intermediate states "Opening" and "Closing" have not senses. The case was that in **IE9** modal is initiating with state **Opening** and never can change to **Opened**, cause depends of transitions if i have setted in parameters "transitionIn" and "transitionOut". Thanks for all.

**Comment by orney21d** [comment]
Maybe is a good option to specify that for the correct operations of the modal the parameters **transitionIn** and **transitionOut** should have the empty values.
Best regards.

**Comment by dolce** [comment]
Thanks, the problem has already been fixed and will be in the next update.
