### ISSUE TITLE
Modal behind overlay when using custom "appendTo"!

### ISSUE THREAD

**Issue by CubE135** [dolce/iziModal#118]
When i use a custom 'appendTo', like this:
`$("#modal").iziModal({
		title: 'Test',
		headerColor: '#88A0B9',
		appendTo: '#content',
		icon: 'fa fa-user'
	});`

The overlay will still append to the 'body' which puts it in front of the modal.
How can i fix this?

**Comment by dolce** [comment]
Put your example online so I can see the problem.

**Comment by CubE135** [comment]
Ok, i put it online:

`https://www.rlsimulator.com/`

click on 'iziModal' in the footer.

**Comment by dolce** [comment]
Try to remove the property: `-webkit-transform: translate3d (0,0,0);`
Or apply: `z-index: 998;` In your Div .col-md-9 inside container-fluid
Which it must resolve.

This happens when some Modal parent structure has its layer order defined in the DOM.

**Comment by dolce** [comment]
But to make it easier to deal with it.
I'll also add an option: **appendToOverlay**
In this way it will be possible to follow the Modal.

**Comment by CubE135** [comment]
That would be awesome :P thank you ^^

**Comment by CubE135** [comment]
Sorry if it sounds rude, but any ETA on that being implemented?
`z-index: 998;` kinda fixed the overlay, but it f***s up other stuff :D

**Comment by dolce** [comment]
Next update

**Comment by dolce** [comment]
Hello @CubE135 , could you test this new version?

[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271784/iziModal_v1.5.1.zip)

You will be able to use **appendToOverlay** option and the new methods: **setContent** and **reset**.
`$('#modal').iziModal('setContent', '<div>Content</div>');`
`$('#modal').iziModal('resetContent');`

And **afterRender** callback:
`afterRender: function(){}`

**Comment by CubE135** [comment]
Is the **appendToOverlay** option a boolean?

**Comment by dolce** [comment]
@CubE135 No.
is the same as appendTo.

**Comment by CubE135** [comment]
Ok thanks :)
