### ISSUE TITLE
Add method "reset"

### ISSUE THREAD

**Issue by Uzumachi02** [dolce/iziModal#119]
`$('#modal').iziModal('reset');`

`reset: function () {
        this.$element.find('.'+PLUGIN_NAME+'-content').html( this.content );
      },`

**Comment by dolce** [comment]
Thanks for the suggestion, I'll review! 👊

**Comment by dolce** [comment]
Hello @Uzumachi02 , could you test this new version?
[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271677/iziModal_v1.5.1.zip)

You will be able to use **appendToOverlay** option and the new methods: **setContent** and **reset**.
`$('#modal').iziModal('setContent', '<div>Content</div>');`
`$('#modal').iziModal('reset');`

And **afterRender** callback:
`afterRender: function(){}`
