### ISSUE TITLE
Request:  Add method to change/create content

### ISSUE THREAD

**Issue by gspears00** [dolce/iziModal#120]
iziModal is awesome!  It is very well suited for static text.  I am looking to use iziModal to show help text for a large number of items on a page.  Each time the user clicks on a help icon next to a field, I would like to read the various attributes from a database (title, subtitle and content/body), and then plug them into iziModal, then do an iziModal.open... There doesn't appear to be a (easy/supported??) way to do this.  This capability would would make iziModal even more useful. If this could make it into the next release, that would be awesome!

Thanks

**Comment by dolce** [comment]
Thanks for the suggestion, I'll review! 👊

**Comment by dolce** [comment]
Hello @gspears00 , could you test this new version?
[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271677/iziModal_v1.5.1.zip)

You will be able to use the new method **setContent**:
`$('#modal').iziModal('setContent', '<div>Content</div>');`

**Comment by dolce** [comment]
Hello @gspears00, could you test this new version?
[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271677/iziModal_v1.5.1.zip)

You will be able to use the new methods **reset** and **setContent**:
`$('#modal').iziModal('setContent', '<div>Content</div>');`
`$('#modal').iziModal('reset');`

**Comment by dolce** [comment]
Hello @gspears00, could you test this new version?
[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271677/iziModal_v1.5.1.zip)

You can use the new methods: **setContent** and **reset**
`$('#modal').iziModal('setContent', '<div>Content</div>');`
`$('#modal').iziModal('reset');`

**Comment by dolce** [comment]
Hello @gspears00 , could you test this new version?
[iziModal_v1.5.1.zip](https://github.com/dolce/iziModal/files/1271677/iziModal_v1.5.1.zip)

You will be able to use **appendToOverlay** option and the new methods: **setContent** and **reset**.
`$('#modal').iziModal('setContent', '<div>Content</div>');`
`$('#modal').iziModal('reset');`

And **afterRender** callback:
`afterRender: function(){}`

**Comment by gspears00** [comment]
I have been involved in something else, but will try to do this today.

 

Thank you,

George S
