### ISSUE TITLE
Conflict between iziToast and iziModal

### ISSUE THREAD

**Issue by Ramin-Bateni** [dolce/iziModal#122]
I used  both `iziToast` and `iziModal` in a project but I think there are some conflict between them.

**For example:**

**If** I put `iziToast.css` below the `iziModal.css` it cause negative side effects on the animation of the background overlay of the opened modal [when i want close the modal].

and

**If** i put `iziModal.css` below the `iziToast.css` it cause negative side effects on opend notification (the title of notification is hide)!

You can see side effect of `iziModal `on title of iziToast in the bellow image (100% key-frame has zero opacity then it hide the title of toast notification):

![image](https://user-images.githubusercontent.com/9051320/29991248-20762e10-8f99-11e7-856d-31780c260ad3.png)

**Is there a patch for these conflicts?
Or should I use these tools with some special order and configs in this cases?**

_In addition: Hey @dolce , I think your plugins are awesome! Bravo!_

**Comment by dolce** [comment]
Thanks @Ramin-Bateni!  I'll analyze! 👊

**Comment by dolce** [comment]
@Ramin-Bateni 
Could you test, please?
[iziModal + iziToast.zip](https://github.com/dolce/iziModal/files/1273373/iziModal.iziToast.zip)

**Comment by Ramin-Bateni** [comment]
Of course, I tested it. 😉
It seems the problems are solved and the toast notifications and modals appears and hides properly _(I wrote `iziModal.css` after `iziToast.css` in my test)._
**Thank you..**

**Apart from this issue:**
**A)** I see 2 error in the _Chrome console_ when I mouse over and mouse leave a toast notification:
![image](https://user-images.githubusercontent.com/9051320/30021498-d0c24ea4-917c-11e7-9d50-11995173be0c.png)

**B)** Also I recommend `Tahoma ` font for `RTL `languages. It is most popular font in the `RTL `websites.
For example 'Lato' and arial are exactly same view in _Persian_ and _Arabic_ language and `Tahoma `has very better view than them to show _Persian_ and _Arabic_ words (`RTL `languages).
```
.iziToast-rtl {
    /*other styles here*/
   font-family: tahoma,'Lato',arial;
}
.iziToast-rtl .iziToast-body strong {
    /*other styles here*/
    font-size: 11px;
}
.iziToast-rtl .iziToast-body p {
    /*other styles here*/
    font-size: 11px;
}

Also I recommend `Tahoma `as default font every where in your plugins (iziToast & iziModal &...) for RTL mode.
```

Is it possible to you fix them?

**Comment by Ramin-Bateni** [comment]
In your attached codes I see another problem too. When I use: `theme: 'dark'`
An inline style override dark background CSS then result is texts with white font color over a white background color:

![image](https://user-images.githubusercontent.com/9051320/30023774-139c89b6-9186-11e7-98c5-c1520e636ed0.png)

**Comment by dolce** [comment]
Yes, but I'm not seeing these errors in the console.
What are your settings?
And try this version:
[iziToast_v1.2.0.zip](https://github.com/dolce/iziModal/files/1275277/iziToast_v1.2.0.zip)

**Comment by Ramin-Bateni** [comment]
I tested both normal and minified versions of the `js `file. Both work the same way.

I found the error condition.
Please test it with `timeout : 0` or `timeout : false` option.
```
iziToast.info({
	title:"My Title"
	,description:"My Description"
	,timeout : 0
});
```

![image](https://user-images.githubusercontent.com/9051320/30036236-9331ead2-91c6-11e7-906e-86082fb6bc1d.png)

**Comment by dolce** [comment]
Now I've been able to replicate the issue.
Fixed. thank you

**Comment by dolce** [comment]
Now I've been able to replicate the issue.
See if it's working..
[iziToast v1.1.2.zip](https://github.com/dolce/iziModal/files/1276036/iziToast.v1.1.2.zip)

**Comment by dolce** [comment]
Now I've been able to replicate the issue.
See if it's working..
[iziToast v1.2.0.zip](https://github.com/dolce/iziModal/files/1276037/iziToast.v1.2.0.zip)

**Comment by Ramin-Bateni** [comment]
Now it's OK
Thank you...
