### ISSUE TITLE
Is it possible to you provide a iziModal.confirm function?

### ISSUE THREAD

**Issue by Ramin-Bateni** [dolce/iziModal#123]
Hi @dolce ,
I know I can make a custom modal with some buttons (Yes,No,OK,Cancel &...) to make a confirm modal by iziModal plugin but I ask is it possible to you provide a special `iziModal.confirm` function?

Just like` iziToast.info`,` iziToast.warning` and ... that you made for your `iziToast `plugin but with some ability to handle click events on the defined buttons.

I have seen this feature in some other modal plugins like [bootbox](http://bootboxjs.com/examples.html).
Thank you in advance...

**Comment by dolce** [comment]
Hello!
Confirm button on iziModal?
No, because the modal plugin does not create footer with linked buttons. Each one customize your own.
What I'm creating is **iziToast.question**, which should create a custom alert for questions.
thanks

**Comment by Ramin-Bateni** [comment]
OK,  **iziToast.question** can be that confirm dialog that i mean too. I need it in my project.
Do you think when to get ready?

**Comment by dolce** [comment]
You can customize **iziModal** anyway you want, with decision buttons and so on.
And in **iziToast** I was already working on Overlay options for the plugin. 
```
overlay: false,
overlayClose: false,
overlayColor: 'rgba(0, 0, 0, 0.6)',
closeOnEscape: false,
```
Would you like to test?
[iziToast v1.2.0.zip](https://github.com/dolce/iziModal/files/1290341/iziToast.v1.2.0.zip)

**Comment by Ramin-Bateni** [comment]
Yes the overlay works well.
Although, in the question function some properties such as `timeout `and `buttons `not working yet.

**Comment by dolce** [comment]
Did you use the correct settings?
ex.
```
    iziToast.question({
        overlay: true,
        toastOnce: true,
        id: 'question',
        title: 'Hey',
        message: 'Are you sure?',
        position: 'center',
        buttons: [
            ['<button><b>YES</b></button>', function (instance, toast) {

                instance.hide({ transitionOut: 'fadeOut' }, toast);

            }, true],
            ['<button>NO</button>', function (instance, toast) {

                instance.hide({ transitionOut: 'fadeOut' }, toast);

            }]
        ]
    });
```

**Comment by Ramin-Bateni** [comment]
Yes, it show the toast but `timeout: false` and `timeout: 0` not working!
If I use `timeout: 0` in the options to prevent timeout on the question then it show the toast and hide it exactly the same moment.

**Comment by dolce** [comment]
@Ramin-Bateni. Could you test again?
[iziToast v1.2.0.zip](https://github.com/dolce/iziModal/files/1294008/iziToast.v1.2.0.zip)
thanks

**Comment by Ramin-Bateni** [comment]
Now, it works well...
Thank you

**Comment by dolce** [comment]
Yes, thanks for the messages.
