### ISSUE TITLE
Ajax is not working

### ISSUE THREAD

**Issue by hugoren** [dolce/iziModal#127]
According to the website guide
window.actionEvents = {
        'click .job_console': function (e, value, form_data) {
            $('#modal_console').iziModal('open', function (modal_console) {
                modal_console.startLoading();
                $.get('/file', function (data) {
                      $("#modal_console .iziModal-content").html(data);
                      modal_console.stopLoading();
                });
            })
        }
    }
Modal is open, but ajax doesn't work？
Js is not wrong
Thank you for your reply

**Comment by emog** [comment]
The example is different. In the example the function is passed in modal initialization after that you could make   modal_console.iziModal('open');
