### ISSUE TITLE
multiple modal

### ISSUE THREAD

**Issue by ebabra** [dolce/iziModal#129]
Hi, Thanks for Modal I am using it inside expandable link for introduction of different products, I have problem with creating multiple modal. here is my code for 2 modals which opens just one:

// example for 2 different modals
        window.onload = function () {

          var a = document.getElementById("margarin_link");
		  var b = document.getElementById("gluten_link");
		  

        a.onclick = function () {
			$("#margarin_modal").iziModal();  
			$(document).on('click', '.trigger', function  (event) {
			event.preventDefault(); 
			$('#margarin_modal').iziModal('open'); 
			$('#margarin_modal').iziModal('reset');
			$('#margarin_modal').iziModal('resetContent');
			});}
			
			
		b.onclick = function () {
			$("#gluten_modal").iziModal();  
			$(document).on('click', '.trigger', function  (event) {
			event.preventDefault(); 
			$('#gluten_modal').iziModal('open'); 
			$('#gluten_modal').iziModal('reset');
			$('#gluten_modal').iziModal('resetContent');
			});}
			
			
			
		  return false;
        }

**Comment by dolce** [comment]
The idea of a modal is always to stay at the top, in front of everything. The iziModal takes this meaning to its structure, so it is not advisable to open more than one at a time, thank you.

**Comment by ebabra** [comment]
Thanks MarceloI want to open only one at the time, but  with different links different content. That means first modal 1 and after close by separate link openin modal 2 etc. Sorry that I am not so good in java script.Many ThanksAvramVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [dolce/iziModal] multiple modal (#129)Von: Marcelo Dolce An: dolce/iziModal Cc: ebabra ,Author The idea of a modal is always to stay at the top, in front of everything. The iziModal takes this meaning to its structure, so it is not advisable to open more than one at a time, thank you.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dolce/iziModal","title":"dolce/iziModal","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dolce/iziModal"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dolce in #129: The idea of a modal is always to stay at the top, in front of everything. The iziModal takes this meaning to its structure, so it is not advisable to open more than one at a time, thank you."}],"action":{"name":"View Issue","url":"https://github.com/dolce/iziModal/issues/129#issuecomment-331512228"}}}
