### ISSUE TITLE
Internet Explorer 11

### ISSUE THREAD

**Issue by claudiopj** [dolce/iziModal#13]
I have experiencing problems on internet explorer 11, modal is not opening...

			$("#modal-custom").iziModal({
					overlayClose: false,
					closeOnEscape: false,				
					width: 600,
					autoOpen: true
			});

In firefox and google chrome is opening

Can you help me?

**Comment by tofanelli** [comment]
Hey @claudiopj ....

I just tested here and it's working flawlessly.... mind to test it using this pens? 

http://codepen.io/tofanelli/pen/EyEkpK



Cheers =)

**Comment by claudiopj** [comment]
Ok! I have found... the error occurs when i set autoOpen to true, then internet explorer takes no action.

**Comment by claudiopj** [comment]
Ok, i find a solution... thank you very much

**Comment by dolce** [comment]
What was your solution @claudiopj ? Thx!

**Comment by claudiopj** [comment]
I need to put in head... 

<meta http-equiv="X-UA-Compatible" content="IE=edge" />

**Comment by dolce** [comment]
ok @claudiopj , thanks!
