### ISSUE TITLE
Navigation for gallery is not workling on mobile

### ISSUE THREAD

**Issue by mpiontek** [dolce/iziModal#143]
Here is the code i use for calling a gallery with iziModal

`
    $(".contentElement__modalgalleryModal").iziModal({
        group: 'modalGallery',
        loop: true,
        headerColor: '#76b72a',
        overlayColor: 'rgba(0,0,0,0.65)',
        bodyOverflow: true,
        navigateArrows: "false"
    });
`
I tried different values for "naviagtionArrows", such as "closeToModal", "closeScreenEdge", "true" and "false" - but on mobile devices i am not able to see the navtigation or to swipe the images. On desktop devices it works very nice.

**Comment by dolce** [comment]
The value of the **navigateArrows** option must be a **boolean** and not a _string_.
`navigateArrows: false`
