### ISSUE TITLE
I can't use iziModal with webpack

### ISSUE THREAD

**Issue by dvelazdiaz** [dolce/iziModal#145]
When I try to load iziModal like a module with `require('izimodal')` I got an error:

`$(...).iziModal is not a function`

I'm using `izimodal 1.5.1` and `jquery 3`. Also I'm loading jquery with webpack ProvidePlugin

```
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        })
```

Any help? Cheers

**Comment by andrew-basilioos** [comment]
you have to force iziModal to use ur jquery version by :
`resolve: {
        alias: {
            'jquery': require.resolve('jquery'),
        }
    }`

**Comment by dvelazdiaz** [comment]
Thanks for your response. I already fixed my issue loading iziModal from bower instead npm

**Comment by RyanGosden** [comment]
I am experiencing the same issues as I had to change the way jQuery was being loaded.
(by using the ProvidePlugin)

` new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        })`

` alias: {
                    'jquery':    'jquery/src/jquery',`

I've tried require('izimodal'), also storing the require to a variable.
No luck as of yet.

Anyone else have this issue?

**Comment by Designer023** [comment]
Ok, none of this worked for me, but what eventually did was:

```
    import iziModal from 'izimodal/js/iziModal';
    $.fn.iziModal = iziModal;
    $("#modal").iziModal();
```

**Comment by tr1s** [comment]
@Designer023 this half helped.

<img width="644" alt="screenshot 2018-10-09 12 01 42" src="https://user-images.githubusercontent.com/19172250/46683031-254f1f80-cbbd-11e8-98b3-b7596e0ec517.png">

The error went from iziModal not being a function, to iziModal not being defined. But everything works if I just use a CDN, so I know my js works. What am I doing wrong?

This is my js

```
$(function () {
  $.fn.iziModal = iziModal;

  $("#modal").iziModal({
    title: 'Test',
    subtitle: 'Test',
    headerColor: '#233a79'
  });

  $(document).on('click', '.trigger', function (event) {
    event.preventDefault();
    $('#modal').iziModal('open');
  });
```

**Where am I supposed to put `$.fn.iziModal = iziModal;`?** I tried putting it in the iziModal.min.js, the top of my custom scripts, inside my jQuery document (like the code above), and where I have all my imports, none of these places seem to work. Yes I am importing the iziModal.min.js and css.

Any help would be greatly appreciated thanks!

**Comment by MichalRemis** [comment]
I hade also trouble geting iziModal work with webpack. Problem was, that iziModal was allways including it's own node_modules/jquery into the pack and then 2 Jqueries were included in output files:

![screenshot 2018-12-13 at 13 47 32](https://user-images.githubusercontent.com/2195772/49939872-4e9e6b80-fede-11e8-89e7-831c559106c3.jpg)

I solved it with an ugly workaround and told webpack to always use iziModal's jquery:

`config.resolve.alias = {
  jquery: path.resolve(
    "./node_modules/izimodal/node_modules/jquery/dist/jquery"
  )
};
`

I suppose it's a problem in iziModal sources because other jQuery plugins works as expected without including it's own jquery

**Comment by dimasi** [comment]
> I hade also trouble geting iziModal work with webpack. Problem was, that iziModal was allways including it's own node_modules/jquery into the pack and then 2 Jqueries were included in output files:
> 
> ![screenshot 2018-12-13 at 13 47 32](https://user-images.githubusercontent.com/2195772/49939872-4e9e6b80-fede-11e8-89e7-831c559106c3.jpg)
> 
> I solved it with an ugly workaround and told webpack to always use iziModal's jquery:
> 
> `config.resolve.alias = { jquery: path.resolve( "./node_modules/izimodal/node_modules/jquery/dist/jquery" ) }; `
> 
> I suppose it's a problem in iziModal sources because other jQuery plugins works as expected without including it's own jquery

+1

**Comment by dimasi** [comment]
+1 (double jquery is my bundle)
