### ISSUE TITLE
modal width&padding

### ISSUE THREAD

**Issue by bestvow** [dolce/iziModal#156]
Maybe use border-box to fix modal width overflow
![image](https://user-images.githubusercontent.com/24888709/33706994-e6a473f8-db70-11e7-8369-112d88b3f845.png)
![image](https://user-images.githubusercontent.com/24888709/33707037-066636a4-db71-11e7-987e-fccf0cdee0de.png)

**Comment by dolce** [comment]
Yes, thanks.
