### ISSUE TITLE
Modal class on close

### ISSUE THREAD

**Issue by blackfyre** [dolce/iziModal#16]
If the original modal container had a class when initialized, it will loose this class once the modal went through an open-close cycle and will be replaced with the `iziModal` class.

Original:
```html
<div id="modal-1" class="customClass">
  <!-- original content -->
</div>
```

New:
```html
<div id="modal-1" class="iziModal" style="...">
  <!-- extended content -->
</div>
```

Preferred solution:
```html
<div id="modal-1" class="customClass iziModal" style="...">
  <!-- extended content -->
</div>
```

**Comment by dolce** [comment]
Yes @blackfyre , it happens to not break the modal animation.
if you want to use a CustomClass, just use the option 'theme'.

```js
$("#modal").iziModal({
    theme: 'customClass',
});
```
