### ISSUE TITLE
$(...).iziModal is not a function - Import in Laravel Webpack

### ISSUE THREAD

**Issue by Adrian-Mazaud** [dolce/iziModal#167]
(I don't speak english very well, sorry)

I tryed many times import this awesome plugin, but i dont understand why it doesnt work, I have this error every time.

![izimodal](https://user-images.githubusercontent.com/13030857/34457887-9dad12c0-edbf-11e7-9800-09aa088a1cb7.png)

I changed many times the webpack configuration and the import method, with require('iziModal'), with import 'iziModal' etc... but no change, so if someone who already worked with Laravel / Webpack Mix and this plugin, can help me, please.
At start i thinked it's jQuery included twice but it's not, i added autload of jQuery in webpack.mix  but it doesn't work, same error.

Thanks, great plugin !

**Comment by RyanGosden** [comment]
Amd and commonsjs support was recently added. Are you  storing result of require statement to a variable? 
Ie: var X = require('izimodal');

**Comment by Adrian-Mazaud** [comment]
My bad, iziModal works great with Webpack, jQuery was included twice, in another js file loaded on page !
