### ISSUE TITLE
data-iziModal-title won't show up unless set in configurations

### ISSUE THREAD

**Issue by obinoob** [dolce/iziModal#169]
Hi, is it possible to pass title throught a element?

`<a href="/budgets/edit/17" class="btn btn-default trigger" data-iziModal-title="test"><i class="fa fa-eye"></i></a>`
Instead set title or subtitle under `$("#modal-iframe").iziModal({});`

According to version 1.3.0 it should be possible, not sure what I'm doing wrong...

**Comment by obinoob** [comment]
I was able to set the title and subtitle with:
$('#modal-iframe').iziModal('setTitle', $(this).data('izimodal-title'));
I wonder if I still miss something...

**Comment by dolce** [comment]
All settings **data-iziModal-*** are defined in the modal div, not in the trigger.
ex:
`<div id="modal" data-iziModal-title="title"></div>`

**Comment by thingNumber1** [comment]
> All settings data-iziModal-* are defined in the modal div, not in the trigger.

I suggest you to fix this example then: http://izimodal.marcelodolce.com/#Iframe

I had the same issue.
