### ISSUE TITLE
Scroll on mobile

### ISSUE THREAD

**Issue by Jon8linden** [dolce/iziModal#17]
Should add a class/style to the body that makes it so when the modal is open only the modal can scroll and not the page. This causes it to have to resize when you scroll on Android and probably iOS when the browser hides or shows the URL bar. 

Should be a simple as adding a no-scroll class to the body and .no-scroll{overflow:hidden;}

**Comment by dolce** [comment]
@Jon8linden  Stay tuned in version 1.3.0, this feature is one about to come  :facepunch:

**Comment by AthletiaTech** [comment]
overflow: hidden is successfully added to body but it seems not to work.
I can still scroll the background...
Do you have any ideas how i can fix this?

**Comment by dolce** [comment]
@AthletiaTech, Unfortunately I have not found a definitive solution yet, but I got something for ios, Only it does not seem to work 100%, you could test too? Upgrade to the latest version(v1.3.3), thanks!

**Comment by CavalcanteLeo** [comment]
I'm suffering this bug too, will try to find a solution too. actually, there are a few more involving mobile, like when you focus on a input

**Comment by dolce** [comment]
@CavalcanteLeo, caso tenha outros bugs, peço que crie uma _issue_ para cada um deles, fica mais simples de corrigi-los, valeu.

**Comment by CavalcanteLeo** [comment]
Arrumei aqui, mas to sem tempo nenhum de fazer uma merge request...
Vou tentar semana que vem...

**Comment by dolce** [comment]
me manda pelo face @CavalcanteLeo, que eu dou uma olhada! inté
