### ISSUE TITLE
iframeURL optional (by event like click) not working with append childs

### ISSUE THREAD

**Issue by MaikeAlame** [dolce/iziModal#19]
Hey,

I got a problem when using font awesome (not because the library). I made this code:

```
<a href="site.com" class="btn btn-primary">
    <i class="fa fa-pencil">
</a>
<div id="modal">
<script>
$("#modal").iziModal({
        iframe: true,
        iframeHeight: $( window ).height()-200,
});
$("a").click(function(e){
        $("#modal").iziModal("open",e);
});
</script>
```
When modal open, the iframe not getting src attribute in some times, other it's normal. It's occur because the pointer click inside the 'i' element or outer, clicking only in 'a' atrribute. In iziModal.js line 303 you getting only `href = param.target.href;`, but target is 'i' element, not 'a'. When I click on 'i', the 'a' element is reffering by currentTarget.

My provisory solution:
`e.target = e.currentTarget`

**Comment by dolce** [comment]
This problem has been fixed and will be updated now in version v.1.3.1. thank you @MaikeAlame for your collaboration.
