### ISSUE TITLE
`timeout` option for an auto close alert like modal?

### ISSUE THREAD

**Issue by hustcer** [dolce/iziModal#2]
Thanks for the great work!
And is there a `timeout` option for an auto close alert like modal?
Sometimes, I just want to display a message and close after a while.
`setTimeout` works but not quite elegant, IMO.

**Comment by dolce** [comment]
Thanks @hustcer, is a good idea. Marked to next update.

**Comment by dolce** [comment]
The new update **(v.1.1.0)** is ready, @hustcer. Added 2 more new features, including this one you suggested. Come check it out.

**Comment by hustcer** [comment]
@dolce Great, Thanks!
