### ISSUE TITLE
ScrollHeight

### ISSUE THREAD

**Issue by danielbarion** [dolce/iziModal#20]
Após atualizar da V 1.20 para a 1.30 eu obtive o seguinte erro, porém efetuei o downgrade para a 1.20 e continuei a usar, normalmente. Notei que a versão 1.31 havia sido lançada, fiz o update e o erro permanece, novamente efetuei o downgrade para continuar com o projeto sem interrupção.

Error:
> $Arquivo.js: 63 Uncaught TypeError: Cannot read property 'scrollHeight' of undefined

* https://github.com/dolce/iziModal/blob/master/js/iziModal.js

Identifiquei que no arquivo acima, a única vez em que scrollHeight aparece é na linha 777 do arquivo em JavaScript:

```javascript
 contentHeight = this.$element.find('.'+PLUGIN_NAME+'-content')[0].scrollHeight,
```

Sou leigo em JS para mexer livremente no código, essas foram as informações que consegui obter, por favor dê uma verificada.

Abraço, Daniel Barion

**Comment by dolce** [comment]
Olá @danielbarion, agradeço o contato.. poderia me dizer mais sobre o ocorrido?
Quando isso ocorre? quando é aberto o modal? qual navegador? e poderia subir um exemplo simples no CodePen, para que eu consiga analisar? valeu

**Comment by danielbarion** [comment]
Sim @dolce, claro.

`http://codepen.io/danielbarion/pen/XKOKVK`

Porém ele não mostrou o erro (começo a pensar que o erro seja no projeto, porém com a versão 1.20 do IziModal ele não apresenta mensagem alguma de erro no console e funciona normalmente.

No exemplo do CodePen, estou puxando o jquery direto do meu servidor (js e css do seu pois o meu está com a versão 1.20).
O código do exemplo é uma parte do que estou usando pra terminar o projeto.

Para ser mais específico, estou utilizando ele para troca de senhas, pesquisas e irei passar a página de feedback que o outro programador fez também.

(Botão direito do mouse -> busca avançada -> modal) é um dos exemplos de como estou utilizando-o).

Se precisar de algo, screenshot ou alguma parte específica/todo o código de como estou usando o plugin, é só me dizer

**Comment by dolce** [comment]
Desculpe a demora @danielbarion , estava de férias.
Conseguiu resolver usando as versões mais recentes do plugin?
No código não tem nenhuma alteração significante nesta função, poderia enviar uma print?

**Comment by danielbarion** [comment]
Sem problemas @dolce, não consegui.
Creio que não tenha, mas fiz upload em uma pasta no Imgur com as prints do site e do código fonte:

`http://imgur.com/a/ZiAsN`

Eu fiz um array com os valores para não precisar ficar "navegando" pelo arquivo a procura da configuração específica da modal, mas creio que isso não interfira em algo...

Assim que visualizar, se possível, **salve** as imagens e me notifique para que eu possa **apaga-las** do Imgur.

Se precisar de mais alguma informação, é só me marcar aqui,
Obrigado

**Comment by dolce** [comment]
Bom dia @danielbarion, pode apagar as imagens.
Este teu projeto está online? se não, conseguiria restringir o acesso somente deste trecho ao meu ip para que eu consiga acessá-lo?

**Comment by danielbarion** [comment]
Bom dia @dolce, ok.

Sim sim, [Pismire](http://pismire.solutions/), porém estou usando a versão do `iziModal | v1.2.0` no servidor e um plugin do Laravel para "minify" os arquivos e mesclar outros (para diminuir as requisições).

Enfim, eu comentei o `.htaccess` das pastas da **CDN** para você acessar a estrutura e como estou utilizando o plugin.

>[JavaScripts](http://pismire.solutions/cdn/js/)
>[CSS](http://pismire.solutions/cdn/css/)

Note que nem todos os JS e CSS estão em uso na versão atual da plataforma (alguns serão removidos por inutilização e outros serão usados após implementarmos algumas ideias que estão anotadas).

Se preferir, após o almoço eu posso comentar o código com o plugin do Laravel e atualizar para a versão atual do IziModal (onde ocorre o erro) para melhor análise.

**Comment by danielbarion** [comment]
**IziModal.blade.php**

````php
{{-- Modals --}}

  {{-- Ajax Message --}}
  <div id="Pismire-ajx--message" class="iziModal"></div>
  {{-- //Ajax Message --}}

  {{-- Primeiras Divs --}}
  <div id="Pismire-N" class="iziModal"></div>
  <div id="Pismire-N2" class="iziModal"></div>
  {{-- //Primeiras Divs --}}

  {{-- Account Unverified--}}
  @if(Auth::Check() && Auth::user()->email_verified == 'no_email_verified')
    <div id="Pismire-N3-Account-Confirm" class="iziModal"></div>
  @endif
  {{-- //Account Unverified--}}

  {{-- Deactive Account--}}
  @if(Auth::Check())
  <div id="Pismire-Confirm-D-Account" class="iziModal">
    <section>
      <form action="#" method="post" class="ajx-deactivate_account--submit">
        <input type="password" placeholder="Password" name="password" id="password">
        <label for="check">
            <input type="checkbox" name="checkbox" id="check" value="1"> 
              Estou ciente de que ao desativa-la, ninguém poderá visitar meu perfil.
        </label>
        <footer>
            <button data-iziModal-close>Cancelar</button>
            <button class="submit" style="background-color:red;">Confirmar</button>
        </footer>
      </form>
    </section>
  </div>
  @endif
  {{-- //Deactive Account--}}

  {{-- Advanced Search Modal --}}
  <div id="Pismire-ASModal" class="iziModal">
      @include('desktop.search.AdvancedSearch')
  </div>
  {{-- //Advanced Search Modal --}}

  {{-- Feedback Modal --}}
  <div id="Pismire-FeedbackModal" class="iziModal">
      @include('desktop.Feedback')
  </div>
  {{-- //Feedback Modal --}}

  {{-- Change Avatar Modal --}}
  @if(Auth::Check())
  <div id="Pismire-ChangeAvatarModal" class="iziModal">
      @include('desktop.modals.ChangeAvatar')
  </div>
  @endif
  {{-- //Change Avatar Modal --}}

  {{-- Change Cover Modal --}}
  @if(Auth::Check())
  <div id="Pismire-ChangeCoverModal" class="iziModal">
      @include('desktop.modals.ChangeCover')
  </div>
  @endif
  {{-- //Change Cover Modal --}}
  {{-- Indicações Perfil --}}
  @if(Auth::Check())
  <div id="Pismire-IPerfilModal" class="iziModal">
      @include('desktop.modals.MeRecommends')
  </div>
  @endif
  {{-- //Indicações Perfil --}}

  {{-- Seguidores Perfil --}}
  @if(Auth::Check())
  <div id="Pismire-SPerfilModal" class="iziModal">
      @include('desktop.modals.MeFollowers')
  </div>
  @endif
  {{-- //Seguidores Perfil --}}

  {{-- Seguidores Perfil --}}
  @if(Auth::Check())
  <div id="Pismire-BlockListSettings" class="iziModal">
      @include('desktop.modals.BlockUser')
  </div>
  @endif
  {{-- //Seguidores Perfil --}}
  
  {{-- Change Password - Settings --}}
  @if(Auth::Check())
  <div id="Pismire-PasswordChange" class="iziModal">
      @include('desktop.modals.ChangePassword')
  </div>
  @endif
  {{-- //Change Password - Settings --}}



{{-- //Modals --}}

````

**Comment by dolce** [comment]
Sim @danielbarion , prefiro que coloque em funcionamento uma página sua com o izimodal na última versão, assim consigo verificar melhor o que ocorre..

**Comment by danielbarion** [comment]
Fiz a atualização para a versão mais recente e o erro não tornou a ocorrer, ocorreu somente na versão **1.30** e **1.3.1** como citei acima.

Caso outra pessoa mencione ter o mesmo erro nos updates, pode manter aberto, se for somente eu, pode dar como resolvido.

Obrigado pela assistência e suporte, qualquer coisa torno a entrar em contado.

Qualquer coisa, estou a disposição, abraço.

**Comment by dolce** [comment]
Que bom que está resolvido @danielbarion, valeu! até mais!
