### ISSUE TITLE
Refresh with event target

### ISSUE THREAD

**Issue by MaikeAlame** [dolce/iziModal#22]
Hey again,

I have one problem when using iframe. The modal is open and I do a refresh on page, but this call a alert saying:
"failed to find iframe URL"

**Comment by dolce** [comment]
hello @MaikeAlame, try using the option: iframeURL: "http://www.site.com";

**Comment by MaikeAlame** [comment]
I can if I destroy / construct. My url is dynamically seted with a global statement in app. That's why I using the event target property

**Comment by dolce** [comment]
@MaikeAlame, sorry about the delay, I was on vacation.
I do not know if I understand. But if you destroy and instantiating again, the address for event will also continue working.
And if the modal is open, the address that will be opened is the iframeURL option.

**Comment by MaikeAlame** [comment]
I don't remember exactly what happened, but if modal is open and I refresh the page, the modal open automatically and the event is not triggered by <a> with href="link", so my code apresents that alert with the code:

```
$("a").click(function(e){
    // alert($(this).attr("href");
    $("#modal").iziModal("open",e);
});
```
I resolve this with:
`if(window.location.hash) window.location.hash = "";`

Maybe a prevent is better than alert, just a idea. Thanks, good plugin

**Comment by dolce** [comment]
Yes, it opens because of history option.
But u can use "_**history**: false_" to disable the hash. And if the modal automatically open is not a problem, just also use the option **_iframeURL_**: "http: // ...."  that there will not display the alert.

**Comment by MaikeAlame** [comment]
Looks like **history** solve the problem perfectly.
