### ISSUE TITLE
"Opened" event not working when a transition is defined.

### ISSUE THREAD

**Issue by marcoarib** [dolce/iziModal#23]
Making some tests with events, I noticed that the "Opened" event not working when a transition is defined. Looking at the code I can see that you applied the "animation Event" to the "wrap" element, not on "modal" element:

`that.$element.find('.'+PLUGIN_NAME+'-wrap').one(animationEvent, function () {`

I tried:

`that.$element.one(animationEvent, function () {`

Works good until by now.
What do you think?

Thank you for this awesome plugin.

Greetings from Minas Gerais.

**Comment by dolce** [comment]
Olá @marcoarib, eu fiz diversos testes e o evento "**Opened**" e está funcionando normalmente, tanto com o event como com a option _onOpened_. Existe um pequeno delay mesmo que é natural dele por esperar a animação terminar.
Eu não posso remover do "-wrap" pois se não vai dar uma pequena quebra/pulo nas animações.
Obrigado pelo comentário! abrçs

**Comment by marcoarib** [comment]
Você está certíssimo. Testei aqui está funcionando normalmente. Devo ter feito alguma merda enquanto mexia. Estava tentando colocar um "map" e estava tentando usar o evento "Opened" para renderizar o mapa somente após o modal ser totalmente aberto.

Mil desculpas pelo minha observação falha.

Um abraço.

**Comment by dolce** [comment]
rs, tranquilo @marcoarib, espero que use e abuse do plugin, abraço!
