### ISSUE TITLE
"Icon element" is added even when not defined

### ISSUE THREAD

**Issue by marcoarib** [dolce/iziModal#24]
What do you think about inserting the "header-icon" element only when it's defined?
Maybe changing:

From:
`if (options.icon !== null){`

To:
`if (options.icon !== null && options.icon !== ""){`

If the icon element is always inserted, but it is empty, the element causes a space problem:

![header icon](https://cloud.githubusercontent.com/assets/7269109/18027863/fdae5006-6c44-11e6-85a1-cc11ead865ae.png)

Thanks.

**Comment by dolce** [comment]
Thanks for your feedback @marcoarib, I'll check.
