### ISSUE TITLE
What support for browsers?

### ISSUE THREAD

**Issue by leonardovff** [dolce/iziModal#25]
What browsers are supported?
I did not find this information.

**Comment by dolce** [comment]
Olá @leonardovff , a informação que está no readme é: "todos os navegadores modernos."
IE9+, Opera, Firefox, Chrome, Safari..
Na real não consegui realizar testes em todos que eu gostaria. Então estou esperando o feedback da galera que possa vir a reportar novos possíveis bugs.
abçs

**Comment by leonardovff** [comment]
Olá @dolce 
Não achei isso no readme.
Vou testar nos browsers, encontrando algo eu reporto.

**Comment by dolce** [comment]
@leonardovff, a informação que mencionei, só está na página do plugin, mas pretendo ser mais descritivo em relação a quais navegadores foi testado e colocarei em ambos canais.
Obrigado pela colaboração, fico no aguardo do seu feedback!
