### ISSUE TITLE
fluid youtube embed

### ISSUE THREAD

**Issue by anybany** [dolce/iziModal#26]
Hi, is it somehow possible to make a modal with a youtube embed fluid?
Right now i have the modal have width: 70%
but the iframeHeight is always fixed.

Is there any workaround or trick to have the height relative to the modal width?

thanks a lot :)

**Comment by dolce** [comment]
@anybany , unfortunately, it is not yet possible, but regardless, the modal is always centered and with adjusted height, see the attachment.

![iframeheight](https://cloud.githubusercontent.com/assets/2837790/18204598/fea0ed76-70f3-11e6-87f1-f5c327d8455c.png)
