### ISSUE TITLE
Media query generation

### ISSUE THREAD

**Issue by JumboLove** [dolce/iziModal#34]
I'm running into an issue when generating media queries that keeps the modal at 100% on the screen.

When I debug the  codepen: http://codepen.io/tofanelli/pen/mEjBJG

I can see that the media query sets max-width: to 600px so that it matches the width of the modal.

On my site, I get an error due to the calculation of that.$element.outerWidth(), it never ends up being the width that I set in the options, so the media query is never applied.

Wouldn't a better solution to set the media query width to the same value passed into the options?

I can make a PR for a fix, but I'm unsure if there is some logic involved that I might be missing.

**Comment by dolce** [comment]
I'll check, thanks

**Comment by dolce** [comment]
You could put his example in codepen? thanks
