### ISSUE TITLE
Gallery support

### ISSUE THREAD

**Issue by wojtek1150** [dolce/iziModal#4]
Hello,

Great job with plugin. Simple and elegant.

It will be great to see gallery support in next version - navigation arrows between another modal's. Maybe on rel="gallery" attr in link?

Greetings, W

**Comment by daltonrooney** [comment]
I'd like to add my +1 on this as well.

**Comment by dolce** [comment]
Stay tuned in version 1.3.0, this feature is one about to come  :facepunch:

**Comment by daltonrooney** [comment]
🙌
