### ISSUE TITLE
Cannot read property 'options' of undefined(…)

### ISSUE THREAD

**Issue by octavioamu** [dolce/iziModal#43]
When a url has a hash is not a modal id the console print this error

**Comment by dolce** [comment]
which line?

**Comment by octavioamu** [comment]
I think the problem is in 885 because  if (typeof data !== 'undefined')  will be true even if not a modal id in the hash

**Comment by dolce** [comment]
It's just a console.error, and have a try catch there.. 
But has been changed in the repository, try download again, thanks

**Comment by octavioamu** [comment]
Thanks buddy!! Im enjoying use your modal.

**Comment by dolce** [comment]
I'm glad you're enjoying it! 👊
