### ISSUE TITLE
Opening Animating glitching after a few opens

### ISSUE THREAD

**Issue by captainswain** [dolce/iziModal#48]
Hi all!

I just started using iziModal(amazing), but i'm having issues with the open animation. After a few clicks it gets glitched and the modal opens larger and then abruptly resizes smaller.

Here is a gif of it in action, the slide is the intended animation:

![Image of Issue](https://i.imgur.com/R4wn9Jv.gif)
my js:

```javascript

$("#modal").iziModal({
    overlayClose: true,
    width: 600,
    overlayColor: 'rgba(0, 0, 0, 0.6)',
    transitionIn: 'bounceInDown',
    onOpened: function() {
        //console.log('onOpened');
    },
    onClosed: function() {
        //console.log('onClosed');  
    }
	});
	$(document).on('click', '#trigger', function (event) {
    event.preventDefault();
    $('#modal').iziModal('open');
});
```
My modal html
```html
<div id="modal">
<section class="container" id="email">
<form>
  <fieldset>
    <label for="nameField">Name</label>
    <input type="text" placeholder="John Doe" id="nameField">
    <label for="emailField">Email</label>
    <input type="text" placeholder="john@doe.com" id="emailField">
    <label for="commentField">Message</label>
    <textarea placeholder="Hi CJ …" id="commentField"></textarea>
    <div class="float-right">
      <input type="checkbox" id="confirmField">
      <label class="label-inline" for="confirmField">Send a copy to yourself</label>
    </div>
    <input class="button-primary" type="submit" value="Send">
  </fieldset>
</form>
</section>
</div>
```

If anyone could help me resolve this, I would be ecstatic.

Thanks!

**Comment by dolce** [comment]
Hello @captainswain , Is it in the latest version? v1.4.0+ If so, could you provide a link to access this page?

**Comment by captainswain** [comment]
Hi @dolce, after more tinkering I found my problem. I mistakenly pulled jquery 3 into my project. I reverted to 2.2.4 and every worked itself out!

Thanks for the Swift issue response I appreciate it !

**Comment by dolce** [comment]
You're welcome! 👊
