### ISSUE TITLE
@2x icons

### ISSUE THREAD

**Issue by aarongarciah** [dolce/iziModal#5]
First of all, congratulations for this nice modal 😃 This is just a suggestion. Would be great to have @2x ready icons. In the iframe and alert examples the close icon doesn't look good on a retina display (MacBook Pro with retina display and iPhone 6).

<img width="766" alt="screen shot 2016-07-19 at 11 38 59" src="https://cloud.githubusercontent.com/assets/7225802/16945447/6a59c938-4da5-11e6-8073-22233fe31424.png">

Thanks for sharing!

**Comment by dolce** [comment]
v1.2.0 ready with retina display support. You could check ok? Thanks for your feedback.

**Comment by aarongarciah** [comment]
Looks awesome! Thanks you.
