### ISSUE TITLE
Failed to find URL (sem iframeURL)

### ISSUE THREAD

**Issue by johanguse** [dolce/iziModal#52]
Se eu removo o parametro iframeURL do JS ele não pega o href... Também preciso fazer eles em grupo.
Estou fazendo errado? Abaixo meu pen teste

Pen: http://codepen.io/johanguse/pen/yVxOKd

**Comment by dolce** [comment]
@johanguse , altere '*this*' para '*event*' nesta linha:
`$("#modal-iframe").iziModal('open', event);`

E para aplicar as opções de grupo, só seguir este modelo:
http://codepen.io/dolce/pen/mEadZK
Abs

**Comment by johanguse** [comment]
Que falta de atenção....

Mas o grupo que eu quero fazer é de iFrame, carregando vídeo, aí preciso colocar o vídeo direto no html dentro de uma div? Se eu embledar o video no html, vai pesar...

No pen tem exemplo, tá funcionando só nao agrupa: http://codepen.io/johanguse/pen/yVxOKd

**Comment by dolce** [comment]
Veja se é isso que queria:
http://codepen.io/dolce/pen/RoYLYj

Ah e mais tarde vou soltar a versão 1.4.2 com algumas melhorias..
por ex. vc poderá passar todas as options por data attributes.

**Comment by johanguse** [comment]
Show! Era isso sim, muito, muito obrigado!
