### ISSUE TITLE
Two iziModal bug on close

### ISSUE THREAD

**Issue by MaikeAlame** [dolce/iziModal#53]
Hey,

I having a problem here with two iziModal opened. One is just a modal with form, but the second is a alert modal with timeout. So, whats happens is when the alert timeout reach to zero and close, the first modal with form is close too.

In the url you can see whats happen:
1.  url#modalForm - when modal form open.
2.  url#modalTimeout- when alert open.
3.  url# - when alert close by timeout, closing the modalForm together.

**Comment by dolce** [comment]
@MaikeAlame, Are you opening two Modals together?
If so, it is wrong, the plugin does not work that way.

**Comment by MaikeAlame** [comment]
Ha ok. Yep, I tried with two, a modal to form and a alert to errors. Maybe with Toast can do it.

**Comment by dolce** [comment]
Yes! ;)
