### ISSUE TITLE
Width/Height Calculation Problem

### ISSUE THREAD

**Issue by davidbwaters** [dolce/iziModal#56]
Hi, since the 1.4.2, I'm having an issue where the modal is flush on the bottom right on first open but is correctly centered on and after second open.  I've tried with different content, and the result is the same.  Before the update, the content was horizontally centered correctly but the height was 100% regardless of content size.  Now, the height/width is being calculated correctly, but not centered correctly.

Also, a suggestion: if there was a parameter to set height as well as width, that would be useful (especially with this issue present).  Thanks.

**Comment by dolce** [comment]
@davidbwaters , could you put this example somewhere so I can see it?
