### ISSUE TITLE
disable close button on header

### ISSUE THREAD

**Issue by LostNCG** [dolce/iziModal#58]
How can I disable/hide close button auto generated by iziModal-header, modal need to hold on before the request end

**Comment by dolce** [comment]
In the options is not possible yet.  But for now you can use css to hide it.
`
.iziModal .iziModal-button-close{
    display: none !important;
}
`

**Comment by LostNCG** [comment]
ya, I use this way now, but I think this should be an enhancement in your plan.
Anyway, this is an awesome modal & toast plugins I have ever seen, thanks for develop it
