### ISSUE TITLE
npm & bower

### ISSUE THREAD

**Issue by rntdrts** [dolce/iziModal#6]
Boas Marcelo,

esta biblioteca é top, quando é que pensas em publicar isto no npm e no bower?

Cumprimentos de Portugal,

Renato Duarte.

**Comment by dolce** [comment]
Boa noite @rntdrts !
já foi publicado no NPM e no Bower! Poderia testar e me dar um feedback se está tudo ok?
obrigado.

**Comment by rntdrts** [comment]
Bom dia @dolce,
está perfeito :+1:, muito obrigado. :smiley:
