### ISSUE TITLE
$window.off is not a function ?

### ISSUE THREAD

**Issue by lewren** [dolce/iziModal#60]
Hi!

Not sure what I'm doing wrong when trying to get iziModal up and running. Have downloaded the zip and put an index.html as testfile into the extracted dir with the following content of the index.html:
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="css/iziModal.min.css">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script src="js/iziModal.js" type="text/javascript"></script>

</head>

<body>

<a href="https://github.com/dolce/iziModal" class="trigger">Modal</a>

<div id="modal">
    
</div>

<script type="text/javascript">
$("#modal").iziModal();
$(document).on('click', '.trigger', function (event) {
    event.preventDefault();

});
</script>
</body>
</html>

But this tells me in the console:
TypeError: $window.off is not a function
TypeError: $(...).iziModal is not a function

Neither does a click trigger the event.

Would greatly appreciate help!

**Comment by lewren** [comment]
Hm, I pasted the whole HTML document (only 35 lines), but it was removed from my post apparently.

**Comment by dolce** [comment]
Can you put the example online? Codepen or other..
