### ISSUE TITLE
Problems on Reopen

### ISSUE THREAD

**Issue by PedroLopes16** [dolce/iziModal#61]
Hey there!

I'm having some problems with the modal... Everything opens fine, but when i close it and reopen it, everything gets messed up... You can see the images...

![untitled-1](https://cloud.githubusercontent.com/assets/22889829/22310271/07a3b7a0-e34f-11e6-88d3-186d9d1e57ae.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/22889829/22310272/07a62daa-e34f-11e6-8097-6340f6d1def7.jpg)

**Comment by dolce** [comment]
Could you send the link so I can see the problem?

**Comment by PedroLopes16** [comment]
www.pedro-lopes.com

**Comment by dolce** [comment]
@PedroLopes16 , tente colocar a div  **item-content** antes da div **swiper slider**

![captura de tela 2017-02-13 as 11 15 45](https://cloud.githubusercontent.com/assets/2837790/22884811/e81c366c-f1dd-11e6-9caa-3d09cd3e1365.png)

**Comment by dolce** [comment]
Ou aplique **overflow:hidden** pra **item-content** ou tente definir uma altura à ele.
Parece que  o modal não está conseguindo calcular seu interior por causa do conteúdo de **item-content**.

**Comment by PedroLopes16** [comment]
@dolce, É igual :/

**Comment by dolce** [comment]
https://github.com/dolce/iziModal/releases/tag/v1.5.0
