### ISSUE TITLE
Modal closes on page scroll

### ISSUE THREAD

**Issue by JohnRipple** [dolce/iziModal#64]
I'm trying to integrate iziModal with fullpage.js, but when the page resizes it moves slightly and this causes the iziModal to close out. Is there any way to stop the modal from closing when the original page scrolls?

**Comment by dolce** [comment]
Could you send the link so I can see the problem?

**Comment by JohnRipple** [comment]
Here is the link.
https://johnripple.github.io/brief.html#about
When you resize the browser window with the modal open it will close.

**Comment by JohnRipple** [comment]
Just an update, when fullpage.js is removed from the code the webpage doesn't close when the page resizes, but as soon as you add it back in and the page size changes the izimodal closes.

Anyone's help with this issues would be appreciated.

**Comment by dolce** [comment]
Please, @JohnRipple. Take a test with this version.
https://www.dropbox.com/s/0gpxhm18v3jnoar/iziModal%20v1.5.0.zip?dl=0

**Comment by dolce** [comment]
Please, @JohnRipple. Take a test with this version.
https://www.dropbox.com/s/uvyufbbaom2noh3/iziModal_v1.5.0.zip

**Comment by JohnRipple** [comment]
I tested out the dropbox code and it didn't change anything with the modal closing problem.

**Comment by JohnRipple** [comment]
I've made the repository public.
