### ISSUE TITLE
setTitle does not work unless title was set on init

### ISSUE THREAD

**Issue by squarewave24** [dolce/iziModal#66]
this took me a while to figure out. 

even if you set title to '' on init, it just won't show. i have to set it to 'dummy' so that i can set it to something relevant to my operation on open. 

            $("#modal").iziModal('setTitle','edit fee rates');

**Comment by dolce** [comment]
I need to change _setTitle_ and _setSubtitle_. Thanks for your feedback, @squarewave24 .
