### ISSUE TITLE
avoid query search modification

### ISSUE THREAD

**Issue by squarewave24** [dolce/iziModal#67]
hi, 

with default iziModal appends #modal-id to url query search. this interferes with other libraries such as angular. 

i was looking through the documentation but can't figure out a way to stop this from happening. is it possible ?

**Comment by squarewave24** [comment]
oop sorry i found the setting, "history: false" :) 

thanks! great library

**Comment by vankov1** [comment]
Keep in mind that you may have a similar issue when the plugin finds that you have some kind of url hash and tries to parse the parameters.
