### ISSUE TITLE
Add option "static margin-top"

### ISSUE THREAD

**Issue by snuuve** [dolce/iziModal#68]
Would be nice to set static margin-top, to avoid modal fying up and down when height of the body is changing.

Here is some preview:
![izimodal_top](https://cloud.githubusercontent.com/assets/9519759/23160015/3fc67a92-f825-11e6-8715-5f335af83423.gif)

**Comment by dolce** [comment]
Hello @snuuve , I'd like you to take a test, okay?

**Comment by dolce** [comment]
Hello @snuuve , Could you test with this version?
https://www.dropbox.com/s/0gpxhm18v3jnoar/iziModal%20v1.5.0.zip?dl=0

**Comment by dolce** [comment]
Hello @snuuve, Could you test with this version?
https://www.dropbox.com/s/uvyufbbaom2noh3/iziModal_v1.5.0.zip

**Comment by snuuve** [comment]
Works perfect for me 👍

**Comment by dolce** [comment]
Great, I'll update the repository soon, thank you.

**Comment by fjeddy** [comment]
Does as advertised, but it seems to only respect one option at the same time, you can't set both values, if top is set, bottom is ignored.

Also, this breaks the scrolling behavior and scroll is not added when needed.

**Comment by dolce** [comment]
Exactly @fjeddy, it should only be used one at a time.

**Comment by dolce** [comment]
Exactly @fjeddy, it should only be used one at a time.
But I made a change and I would like you to test, okay? Maybe that's what you want.

**Comment by fjeddy** [comment]
Re-downloaded the zip, doesn't seem to change anything, margin is still only applied to the top and the scroll is completely gone.

What's the logic in only respecting one option at the time? If i want the top to be 50 and bottom to be 0, wouldn't it then be logical to define the options at such instead of having the library override me?

**Comment by dolce** [comment]
Calm down, I'll still send the modifications here.

**Comment by fjeddy** [comment]
What the F?

**Comment by dolce** [comment]
@fjeddy ?

I just asked if you could test. I asked you to wait because I was adjusting some lines of code. Try it:
[v1.5.0-topbottom.zip](https://github.com/dolce/iziModal/files/888613/v1.5.0-topbottom.zip)

**Comment by dolce** [comment]
@fjeddy ?

I just asked if you could test. I asked you to wait because I was adjusting some lines of code. Try it:
[iziModal-1.5.0-NewTopBottom.zip](https://github.com/dolce/iziModal/files/888640/iziModal-1.5.0-NewTopBottom.zip)

**Comment by fjeddy** [comment]
@dolce Actually, you said you already **had** made the changes, didn't ask me to wait. Hence why i respond that your changes has nothing :P

And thanks, the modifications you made gives the exact behavior i am looking for. But the scrollbar is still broken, it seems like the scroll isn't added to the element at all, which is a problem, as i use the modal to host some very large forms.

**Comment by dolce** [comment]
I did, but I modified it again. I had just seen your request, had no way to modify everything instantly.
Regarding the scrollbar, could you send me a printscreen of this problem?

**Comment by fjeddy** [comment]
@dolce Not sure how it helps, the scrollbar is simply not there. But https://unsee.cc/bupisate/

**Comment by dolce** [comment]
I needed to see to understand better. I'll see if I can fix this in this or next update.

**Comment by dolce** [comment]
@fjeddy, Could you test again? Maybe I have solved it.
[iziModal_v1.5.0_fixTopBottom.zip](https://github.com/dolce/iziModal/files/888689/iziModal_v1.5.0_fixTopBottom.zip)

**Comment by fjeddy** [comment]
Not working, only visible difference is the main body scroller that is now visible and scrollable.

**Comment by dolce** [comment]
https://github.com/dolce/iziModal/releases/tag/v1.5.0
