### ISSUE TITLE
ES6 import doesn't work

### ISSUE THREAD

**Issue by Ernisto** [dolce/iziModal#69]
I tried to import iziModal through ES6 `import` but it was unsuccessful.

> import 'izimodal/js/iziModal.js';

![image](https://cloud.githubusercontent.com/assets/13309012/23258196/3f05458e-f9f1-11e6-9acc-ea92e5f37d55.png)

**Comment by carlosfiori** [comment]
This is probably conflicting with two versions of JQuery, the izimodal is using JQuery 2

@dolce , could you upgrade to Jquery 3?

**Comment by dolce** [comment]
@carlosfiori , @Ernisto .
 Use the latest version. Now it supports the AMD pattern. thx

**Comment by Ernisto** [comment]
@dolce Thanks!
