### ISSUE TITLE
Change transition margin to transform

### ISSUE THREAD

**Issue by snuuve** [dolce/iziModal#70]
For better performance and smoother animations :)

**Comment by dolce** [comment]
@snuuve, The animations already use transform, only the positioning of the modal to the center that does not. Unfortunately, if I also use transform in positioning this will affect the opening and closing animations of the modal.
I have to review this idea better.
Anyway thanks for the feedback.

**Comment by snuuve** [comment]
@dolce Yup, i'm talking about positioning of the modal. Ok, i understand :)
