### ISSUE TITLE
Click events dont fire

### ISSUE THREAD

**Issue by BatenkovT** [dolce/iziModal#71]
I can`t use js datepicker on input inside the modal. I think iziModal blocks all click events inside. How can I fix this?

**Comment by dolce** [comment]
hello @BatenkovT , I'll check, thanks

**Comment by dolce** [comment]
@BatenkovT, Are you using this datepicker?
https://jqueryui.com/datepicker/

**Comment by BatenkovT** [comment]
No, this 
https://github.com/amsul/pickadate.js

**Comment by dolce** [comment]
It's working here.

![captura de tela 2017-03-09 as 12 18 52](https://cloud.githubusercontent.com/assets/2837790/23756493/98a9417c-04c2-11e7-81f0-1841b860fd8c.png)

**Comment by snmhinge** [comment]
Datepicker is not showing?
