### ISSUE TITLE
iFrame Refresh Issue

### ISSUE THREAD

**Issue by X-rapido** [dolce/iziModal#72]
Hello ， I hava a question， if the url is “/iziModal-master/demo.html#tiframeModal” ，when i Refresh it，the page and click button don't work

`&lt;a href="https://www.so.com/" class="tiframe"&gt;Click It&lt;/a&gt;

&lt;div id="tiframeModal" class="iziModal"&gt;&lt;/div&gt;

$("#tiframeModal").iziModal({
    iframe: true,
    iframeHeight: 400
});
$(".tiframe").click(function(e){
   e.preventDefault();
   $("#tiframeModal").iziModal("open",e);
});`

![qq 20170315143042](https://cloud.githubusercontent.com/assets/9986850/23936301/537e992a-098c-11e7-9ecc-5fcf435b6c14.jpg)

**Comment by X-rapido** [comment]
must be have "iframeURL" attributes for initialization?

**Comment by dolce** [comment]
Try to use this 'data' in the Div of your modal
`<div id="modal-iframe" data-iziModal-iframeURL=http://...></div>`
So you do not necessarily have to use the iframeURL option:
