### ISSUE TITLE
Modal does not resize to the content (v1.4.2, 1.5.0 beta)

### ISSUE THREAD

**Issue by luzfcb** [dolce/iziModal#78]
I get the content via ajax, and insert into modal, however, it does not adapt to the content.

on 1.4.2, after closing the modal and opening again, the modal works as expected, and is adapt to the content.

A minimal example demonstrating the problem:

v1.4.2: http://codepen.io/luzfcb/pen/VpqxRy/

v1.5.0 beta: http://codepen.io/luzfcb/pen/peqxmP

v1.5.0 beta with 1.4.2 css: http://codepen.io/luzfcb/pen/VpqgVq

**Comment by dolce** [comment]
@luzfcb , eu vi aqui seu exemplo.
O problema está na classe **.modal** na mesma div do iziModal.
Se você reparar nas propriedades dessa classe vai ver que tem um **bottom: 0px**, dai fica impossível o plugin recalcular sua altura...
![image](https://cloud.githubusercontent.com/assets/2837790/24582714/05a003be-170c-11e7-8238-d65462200be6.png)

E fora isso você está querendo aplicar 2 modais, o iziModal junto com o do bootstrap, não entendi muito bem, mas com certeza ocorreria problemas.
