### ISSUE TITLE
`top` and `bottom` options defect?

### ISSUE THREAD

**Issue by fjeddy** [dolce/iziModal#79]
Hello,

I am working on a modal that consumes more then the height of the screen and therefor goes to the top and bottom covering the entire height.

I want to add a 50px margin between the top and the bottom, making the modal feel more like a modal even tho it's content is larger then the screen size.

Based on my understanding from the docs then the options `top` and `bottom` should do exactly what i want? But from what i can see, then adding the options does absolutely nothing with the CSS on the frontend.

```
$( '#contribute' ).iziModal( {
    title: 'Title here',
    description: 'Description here.',
    history: false,
    headerColor: '#eee',
    restoreDefaultContent: true,
    fullscreen: true,
    overlayColor: 'rgba( 0, 0, 0, 0.6 )',
    width: 960,
    padding: 30,
    bottom: 50,
    top: 50,
    autoOpen: 1
} )
```

Am i doing something wrong in my options? Have i misunderstood the purpose of `top` and `bottom`? Or is it not working like it should?

**Comment by dolce** [comment]
*Top* and *bottom* are features of v1.5.0. You can see in the changelog of the site. Soon I will publish this new version. thx
