### ISSUE TITLE
Using iziModal with tons of (dynamically generated) modals

### ISSUE THREAD

**Issue by garagnoth** [dolce/iziModal#81]
Hi, I love your plugin. Just got one problem with it. What if i have tons of (dynamically generated) modal and initializing each of the modals is not an option.

Suppose that I have the following links:
`<a href="modal-1" class="trigger-Modal">Modal One</a>`
`<a href="modal-2" class="trigger-Modal">Modal Two</a>`
and the modals:
```
<div class="modalContent">
   <div id="modal-1">content one here</div>
   <div id="modal-2">content two here</div>
</div>
```

I tried using the following but it didn't work:
```
    $(document).on('click', '.trigger-Modal', function(event) {
        event.preventDefault();
        var modalCall = $(this).href;
        $(modalCall).iziModal('open', this);
    });
```
and
```
    $('.modalContent').children().each()
        var divID = $(this).ID;
        console.log(divID);
        $(divID).iziModal({
            title: 'A random title',
            subtitle: 'For a random text',
    });
```

**Comment by dolce** [comment]
@garagnoth. Could you put your example in codepen or in another?

**Comment by garagnoth** [comment]
Hi dolce, got it working not using that approach but using data-iziModal-open.

**Comment by ebabra** [comment]
Hi garagnoth
I have same problem, could you please help me also to get to know how you solved it, I can not set links/scripts to read different modal contents and the modal is closing after open itself, I used $('#modal').iziModal('reset'); but it will trigger console error although the modal works ok, but still I have problem to load differents modals with different contents on same page (of course at time only one)
thanks
