### ISSUE TITLE
Js error on 1.5.0

### ISSUE THREAD

**Issue by maikealame** [dolce/iziModal#85]
Hey,

Look this error, it happen at any time when change window and back

iziModal.js:1195 Uncaught TypeError: Cannot read property 'split' of undefined
    at jQuery.fn.init.$.fn.(anonymous function) [as iziModal] (http://gsa.localhost/assets/scripts/frontend.js:53257:24)
    at HTMLDocument.<anonymous> (http://gsa.localhost/assets/scripts/frontend.js:53233:26)
    at HTMLDocument.dispatch (http://gsa.localhost/assets/scripts/frontend.js:5206:27)
    at HTMLDocument.elemData.handle (http://gsa.localhost/assets/scripts/frontend.js:5014:28)

**Comment by dolce** [comment]
@maikealame, em que ocasião ocorre este erro?

**Comment by maikealame** [comment]
@dolce Segue abaixo:

[view]
```
<script>
$(document).ready(function() {
        $("body").on("click",".btnView",function(e){
                e.preventDefault();
                e.target = e.currentTarget;
                if(!e.target.href) return;
                $("#modalTicket").iziModal("setSubtitle", "Ocorrencia 123");
                $("#modalTicket").iziModal("open",e);
         });
 });
</script>
<div id="modalTicket" class="izimodal-iframe" data-icon="fa fa-exclamation-triangle" data-title="Visualizar Ocorrência" data-subtitle="." data-width="1100" data-height="500">
</div>
```

[global.js]
```
$(document).ready(function(){
        $(".izimodal-iframe").each(function(i,e){
                izimodalIframe(e);
        });
});

function izimodalIframe(e){
    $(e).addClass("iziModal").iziModal({
        title: $(e).attr("title") || $(e).data("title") || '',
        subtitle: $(e).attr("subtitle") || $(e).data("subtitle") || '',
        iconClass: $(e).data("icon") || '',
        iconColor: $(e).data("icon-color") || '#FFF',
        headerColor: $(e).data("header-color") || '#337ab7',
        padding: $(e).data("padding") || 0,
        width: $(e).data("width") || $(window).width() / 100 * 80,
        fullscreen: $(e).data("fullscreen") || false,
        openFullscreen: $(e).data("fullscreen-open") || false,
        iframe: true,
        iframeHeight: $(e).data("height") || $( window ).height()-200,
        iframeURL: $(e).data("url") || null,
        history: false,
        autoOpen: false,
        onOpening: function(){
            $(e).find('iframe').load(function(){
                var m = $(this).contents();


                // insert hidden field for interface modal
                var form = $(m).find('form');
                form.find("input._interface").remove();
                form.append(frameModal);


                // aborted to finish modal
                $(m).find("#_modalFrameClose").click(function(){
                    $(window).focus();
                    $(e).iziModal("close");
                });
                $(m).find(".btnModalClose").click(function(ev){
                    ev.preventDefault();
                    $(window).focus();
                    $(e).iziModal("close");
                });

                $(this).resize();
            });
        },
        onClosed: function(){
            document.location.hash = "";
        },
        onOpened: function (e) {
            
        }
    });
}
```

**Comment by dolce** [comment]
@maikealame, tem certeza que é erro do plugin?
Se sim, poderia colocar o exemplo em alguma plataforma debugável?

**Comment by sweell** [comment]
Hi dolce,
i've the same error with jQuery 3.2.1, I think it's incompatible with the new jQuery framework.
Bye, Luigi

**Comment by maikealame** [comment]
@dolce segue
https://jsfiddle.net/maikealame/01xhvvbf/

O erro acontece quando alguma tecla é pressionada (Clique no result container antes)

**Comment by dolce** [comment]
@maikealame, aqui seu exemplo não está rodando..
Só uma dica, você pode adicionar a lib do izimodal (css/js) como external resources, dai não precisaria copiar o plugin inteiro pro exemplo..

**Comment by maikealame** [comment]
@dolce qual link ? não encontrei nenhuma cdn com a versão 1.5
 Faltou salvar, pode olhar novamente

**Comment by dolce** [comment]
erro: Uncaught TypeError: a.indexOf is not a function

Eu vi que está usando as options dessa forma: **$(e).data("icon")** ...
Porque não usa: **data-iziModal-icon"icon"**?

**Comment by maikealame** [comment]
Opa, tenta de novo. Eu esqueci de colocar o jquery migrated em external resources. O erro é exatamente esse quando aperto uma tecla
Uncaught TypeError: Cannot read property 'split' of undefined
    at jQuery.fn.init.t.fn.(anonymous function) [as iziModal]

**Comment by dolce** [comment]
@maikealame, nenhum erro por enquanto aqui. Qual navegador/versão está utilizando?

**Comment by maikealame** [comment]
Edge 14 - Firefox 53 - Chrome 58
Assim: no jsfiddle tu não está dando focus na tela, pq é um iframe a renderização do resultado, tem que clicar no container (iframe) com a renderização (pode ser do lado dos btn, não precisa abrir o modal) depois aperta qualquer tecla e vai ver o erro.

![image](https://cloud.githubusercontent.com/assets/15782847/26358239/452e552a-3fa8-11e7-81a3-773341b2f450.png)

**Comment by karedas** [comment]
The same thing, the error comes on any keydown of the keyboard. It does not matter to initialize izimodal, just include it.

**Comment by dolce** [comment]
Acontece a mesma coisa nesse exemplo?
https://jsfiddle.net/01xhvvbf/8/

**Comment by maikealame** [comment]
Sim, não conseguiu visualizar o erro ?

**Comment by dolce** [comment]
Agora sim @maikealame, ja sei o que é 👍

**Comment by dolce** [comment]
@maikealame , tenta novamente nesse exemplo, veja se o erro persiste.
https://jsfiddle.net/01xhvvbf/12/

**Comment by maikealame** [comment]
Nenhum erro agora. Valeu

**Comment by dolce** [comment]
@maikealame. Show! até o fds eu atualizo o repositório e todas as dependencias. valeu!

**Comment by karedas** [comment]
thanks!

**Comment by dolce** [comment]
https://github.com/dolce/iziModal/releases/tag/v1.5.0

**Comment by evbermudez** [comment]
you may have initialized iziModal and the element that you are targeting doesn't exist on the current page.
