### ISSUE TITLE
fullscreen if mobile device

### ISSUE THREAD

**Issue by sull** [dolce/iziModal#86]
have you ever used this to act differently if ios safari etc vs. desktop screens? 
Like for example opening in fullscreen on mobile but smaller modal if desktop?
Because on smaller screen, I think fullscreen modal is the only sensible setting.

**Comment by dolce** [comment]
Hello @sull.
I can not force everyone, but you can handle this and fire the event:
`$('#modal').iziModal('setFullscreen', true);`

**Comment by sull** [comment]
yep I tested that and am doing it when small screen detected. works great.
