### ISSUE TITLE
Criar Drag and drop para iziModal

### ISSUE THREAD

**Issue by Fogatt** [dolce/iziModal#90]
Boa tarde, 

Estou utilizando o iziModal.js no meu sistema, hoje me deparei com uma questão: Não existe uma opção para arrastar o modal. Existe alguma forma (workaround)  para que eu consiga fazer isto?

**Comment by dolce** [comment]
Hi @Fogatt . The plugin does not support this. Because the purpose of the modal is to always keep centered on the screen. It would have to make some changes in the structure. thanks.
