### ISSUE TITLE
Modal auto close on open when history: false

### ISSUE THREAD

**Issue by PhouvanhKCSV** [dolce/iziModal#91]
I don't know which one i am doing wrong.

with **history: false**, modal auto close when open. 
I don't want to show Hash (#) with modal ID in the address bar.

```javascript
const modal = $('#modal').iziModal({
    overlayClose: false,
    closeOnEscape: false,
    history: false,
});

modal.iziModal('open');
```

**Comment by dolce** [comment]
In version 1.5 the option history is false by default.
