### ISSUE TITLE
Combine with context menu

### ISSUE THREAD

**Issue by larigyn** [dolce/iziModal#93]
Sir,

I tried to call your modal with input fields inside on it, from a context menu (medialize.github.io/jQuery-contextMenu ),  when it appears its shows a lockscreen, I can't input in the fields. 
But when i tried to call your modal from a button clicked, it works. But when i tried to minimized the window  some fields doesn't appear the responsive doesn't works.
`<script>
	$("#supplemental").iziModal({
		title: 'PROJECT PROCUREMENT MANAGEMENT PLAN',
		subtitle: 'Supplemental',
    	// icon: 'fa-dashboard',
    	// icon: '<?php base_url() ?>assets/images/gcj_.png',
    	headerColor: '#88A0B9',
    	theme: 'light',  // light
     	appendTo: '.body', // or false .body      
     	width: 1000,
     	bodyOverflow: true,
     	fullscreen: true,
     	openFullscreen: true,
     	closeOnEscape: true,
     	closeButton: true,
     	overlay: true,
     	overlayClose: true,
     	autoOpen: false,
     	overlayColor: 'rgba(0, 0, 0, 0.6)',
     	timeout: false,
     	timeoutProgressbar: false,
     	pauseOnHover: false,
     	timeoutProgressbarColor: 'rgba(255,255,255,0.5)',
     	transitionIn: ' comingIn',
     	transitionOut: 'comingOut',
     	transitionInOverlay: 'fadeIn',
     	transitionOutOverlay: 'fadeOut',
      //comingIn, bounceInDown, bounceInUp, fadeInDown, fadeInUp, fadeInLeft, fadeInRight, flipInX.
      //comingOut, bounceOutDown, bounceOutUp, fadeOutDown, fadeOutUp, , fadeOutLeft, fadeOutRight, flipOutX.
  });

	$(document).on('click', '.trigger', function (event) {
		event.preventDefault();
		$('#supplemental').iziModal('open');
	});
	
</script>`
clicking the **ADD** button will call the modal
![clicking add](https://user-images.githubusercontent.com/26628446/27138137-5f286a04-5152-11e7-83fb-288d77c31f2f.png)

Then it looks like this... I can't input in the fields :(
![lockscreen](https://user-images.githubusercontent.com/26628446/27138155-6a3288da-5152-11e7-8430-b159655067c3.png)

This sample came from a button. Successfully launch
![modal_fullscreen](https://user-images.githubusercontent.com/26628446/27138189-81a67292-5152-11e7-96cf-4dce5eeda231.png)

**Comment by dolce** [comment]
I would like to see the example online to try to help.

**Comment by larigyn** [comment]
sir,
I already fixed this problem. Thanks for your time.
