### ISSUE TITLE
Large window after loading new content stays on previous position

### ISSUE THREAD

**Issue by Etrimon** [dolce/iziModal#94]
Hi,

I would like to know, if there is a way to let the content for a large window always start from top after loading the iziModal window.

Example: I have content lets say 1600px long using the bodyOverflow : true option. -> I open it and scroll to the botton -> I close the window -> I reopen the window again and it opens again at the bottom of the window (you can see it even on the example page for iziModal), but I would like to let it open always from top of the content.

scrollTop(0) attached to iziModal-wrapper or iziModalContent did not work either for onOpened or onClosed event.

Thank you very much for your answer.

**Comment by dolce** [comment]
I understood @Etrimon .
For now you can use the following code on **onOpened** function:
```
        setTimeout(function(){
            $("#modal .iziModal-wrap").scrollTop(0);            
        },1)
```

**Comment by Etrimon** [comment]
I will try it! Thank you for the answer!

**Comment by Etrimon** [comment]
Your method is sadly not working... (maybe I forgot to say, that I am using it inside Wordpress Ajax Method).

**Comment by dolce** [comment]
I tested this and it worked well.
Try to increase TimeOut time. Also check if it is running on the correct Callback.
