### ISSUE TITLE
Responsive problem

### ISSUE THREAD

**Issue by larigyn** [dolce/iziModal#95]
Sir,

Can you help me to fix this. Thanks :) When I try to get the windows smaller the whole content may not appear.
![modal_fullscreen](https://user-images.githubusercontent.com/26628446/27137811-70760506-5151-11e7-9ae3-03bd32bfecb5.png)
![modal_fullscreen1](https://user-images.githubusercontent.com/26628446/27137818-757a733e-5151-11e7-8ade-ebce5c6faa84.png)

**Comment by dolce** [comment]
@larigyn, I would like to see this example online to help.
