### ISSUE TITLE
Sandbox options for iframe

### ISSUE THREAD

**Issue by ichuprov** [dolce/iziModal#97]
Please add option to specify sandbox options for the iframe.
I need to edit your code to add in the sandbox options I need.
Would be better if they were set through an izimodal option.

**Comment by dolce** [comment]
Is it a Modal generator?
Maybe soon, thank you.

**Comment by earthroot** [comment]
You can do it without editing library code with onOpening function like so:
```
onOpening: function(){
     $('.iziModal-iframe')[0].setAttribute('sandbox', '');
}
```
