### ISSUE TITLE
Background Image/Color

### ISSUE THREAD

**Issue by larigyn** [dolce/iziModal#98]
Sir,
How to change the Background color/image of the modal. I can't find in your documentation. All I can change is the header color.

**Comment by dolce** [comment]
Use o css @larigyn. I'll think about adding in the next version. thanks

**Comment by dolce** [comment]
Use css @larigyn. I'll think about adding in the next version.

**Comment by dolce** [comment]
Use css @larigyn.
```
#modal{
	background: red;
}
```
Maybe I add as an option. thanks
